### ISSUE TITLE
does not build with go release

### ISSUE THREAD

**Issue by XULRunner42** [skelterjohn/go-gb#10]
yebyen@jcurry:~/go-gb/gb$ make
8g -o _go_.8 build.go deps.go gb.go goinstall.go make.go pkg.go gofmt.go runext.go util.go files.go usage.go cgo.go query.go genmake.go 
gb.go:92: undefined: os.Create
gb.go:225: undefined: os.Create
pkg.go:412: not enough arguments in call to os.Open
pkg.go:760: undefined: os.Create
pkg.go:1103: undefined: os.Create
files.go:54: not enough arguments in call to os.Open
files.go:90: not enough arguments in call to os.Open
files.go:105: not enough arguments in call to os.Open
files.go:161: not enough arguments in call to os.Open
files.go:167: undefined: os.Create
files.go:167: too many errors
make: **\* [_go_.8] Error 1

what's new with go since release?

i saw advice to hg pull -u, i will try this... do you suppose it's worth blogging about changes in go since release?

**Comment by XULRunner42** [comment]
you can close this issue if you want, i just tested it and hg pull -u fetches the latest code and makes it build...

**Comment by skelterjohn** [comment]
You can also use https://github.com/skelterjohn/gb-release - I don't know how else to have a version for release and tip at the same time.

**Comment by cdunn2001** [comment]
> I don't know how else to have a version for release and tip at the same time.

Just create a branch called **release**. That's what **goinstall** will use.

You've got some weird stuff going on:

```
.git/packed-refs:cae511e00d4a1ffc3a9322a6e6f8485eb89d2c95 refs/tags/release
.git/packed-refs:062e388a31dce158a7c2e9f8ce786830e918781a refs/remotes/origin/release
```

It looks like you have a local **release** branch already. You should delete the **release** tag and let **goinstall** rely on your **release** branch instead. It will work fine.
`
git checkout latest
git tag -d latest  # delete tag locally
git push origin :refs/tags/latest  # delete tag in repo
git checkout -b latest
git push origin latest
`

**Comment by skelterjohn** [comment]
I'll tackle this when release 59 comes out. Thanks for the tips! I'm pretty novice at git.
