### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by jbrukh** [skelterjohn/go-gb#11]
I get

```
6g -o _go_.6 build.go deps.go gb.go goinstall.go make.go pkg.go gofmt.go runext.go util.go files.go usage.go cgo.go query.go genmake.go 
gb.go:92: undefined: os.Create
gb.go:225: undefined: os.Create
pkg.go:412: not enough arguments in call to os.Open
pkg.go:760: undefined: os.Create
pkg.go:1103: undefined: os.Create
files.go:54: not enough arguments in call to os.Open
files.go:90: not enough arguments in call to os.Open
files.go:105: not enough arguments in call to os.Open
files.go:161: not enough arguments in call to os.Open
files.go:167: undefined: os.Create
files.go:167: too many errors
make: *** [_go_.6] Error 1
```

This is on Darwin with release.r56

**Comment by skelterjohn** [comment]
Hi,

If you take a look at https://github.com/skelterjohn/gb-release then that version should compile with the latest release. I'm not sure how to work both release and tip versions into one repository, so sorry about that.
- John

**Comment by jbrukh** [comment]
Hey John,

Thanks for the tip.  If you'd like to follow both tip and release versions
of Go, why not have two separate branches instead of two separate
repositories?

Thanks,
Jake

**Comment by skelterjohn** [comment]
hmm. What happens if you clone go-gb and then checkout release? I do have two branches on my local git, I just wasn't sure how to push both of them to github...

**Comment by jbrukh** [comment]
You'll need to push your local branches explicitly to github for them to
appear:

   $ git push origin mylocalbranch

You can also do the following: keep two local branches such as "tip" and
"release", then tag them appropriately and push them to github.  Then users
can just checkout by tag.  You do:

```
  $ git checkout release
```

   <do work>
   $ git commit -a -m "Up to date with release.r56."
   $ git tag gb-release.r56
   $ git push origin release --tags

User does:

```
  $ git clone <your repo>
```

   $ git checkout gb-release.r56

--Jake

**Comment by skelterjohn** [comment]
Thanks!

"git checkout gb-release.r56" does it, now.

**Comment by jbrukh** [comment]
Looks great, thanks!

**Comment by jbrukh** [comment]
By the way, great job on the tool, definitely very useful.  I'm writing a
data structures library in multiple packages and I thought I was going to
kill myself with makefiles.  :)

Thanks again,
Jake

**Comment by jbrukh** [comment]
Hey John,

I noticed that gb -t from gb-release.r56 doesn't work; this seems to be due
to the fact that testing.RunTests is no longer an exported function of that
package:

```
_test/_testmain.go:16: undefined: testing.RunTests
```

Any thoughts on this? Maybe just running gotest in each target dir would be
enough...

Thanks,
Jake.

**Comment by skelterjohn** [comment]
Ah, the problem is that I made the r56 version by rolling back some code
rather than tagging when r56 came out... and I tested building but not
testing. The code generated for testing works with tip :)

I'll take a look at this tomorrow.

**Comment by jbrukh** [comment]
No worries, thanks for taking a look.

**Comment by skelterjohn** [comment]
I feel a bit bad, but I solved your issue by waiting for release 57 to come out. You can get it with either the release or gb-release.r57 tag (both are the same as tip when I write this comment).

**Comment by jbrukh** [comment]
Don't feel bad!  Thanks for the heads up.

--Jake
