### ISSUE TITLE
GB doesn't build on weekly 06-23

### ISSUE THREAD

**Issue by bketelsen** [skelterjohn/go-gb#14]
Probably just needs a new weekly tag in Github.

**Comment by skelterjohn** [comment]
You may be using the release version of gb. If your compile error has to do with StringArray, then this is the problem.

The following assumes you installed gb using goinstall, which always grabs the release version:

To use the most up to date gb, which is built against weekly, go to wherever goinstall put the source (probably $GOROOT/src/pkg/github.com/skelterjohn/go-gb) and do "git pull git@github.com:skelterjohn/go-gb.git", and make install.

If that's not the problem, let me know.

**Comment by bketelsen** [comment]
I agree this is the problem.  I thought goinstall looked for a weekly tag in the source if it existed.

**Comment by bketelsen** [comment]
and since I'm here, thanks!!! I love gb.

**Comment by skelterjohn** [comment]
Sorry, not the case (I just double-checked the goinstall source), though I do agree that it would be useful.

**Comment by skelterjohn** [comment]
Thanks!
