### ISSUE TITLE
Generated Makefile error: "Makefile:41: *** missing separator.  Stop."

### ISSUE THREAD

**Issue by bmatsuo** [skelterjohn/go-gb#29]
Generated makefiles produce the error `Makefile:41: *** missing separator.  Stop.` on Go branch r60. I inspected things a little more.

```
$ tail Makefile
include $(GOROOT)/src/Make.cmd

# gb: copy to local install
$(GBROOT)/bin/$(TARG): $(TARG)
    mkdir -p $(dir $@); cp -f $< $@
command: $(GBROOT)/bin/$(TARG)

# gb: local dependencies
$(TARG): $(GBROOT)/_obj/view.a
<<<<<<< local
$
```

Looks like an unhandled merge conflict or something.

**Comment by skelterjohn** [comment]
It doesn't look like this for me. Have you ever edited the code? Try a goinstall -u -clean to get the latest code.

**Comment by bmatsuo** [comment]
hmm. I did just before I openned the issue. I just tried deleting the repository all together

```
$ cd /home/bryan/src/go/src/pkg/
$ yes | rm -r go-gb.googlecode.com/
$ cd -
/home/bryan/Archive/Code/Go/Owned/wiki
$ goinstall -u -nuke go-gb.googlecode.com/hg/gb && gb --makefiles && gomake
Running gb in workspace /home/bryan/Archive/Code/Go/Owned/wiki
assets ignored
'build' exists; overwrite? (y/n) y
(in .) generating build script
'helper/Makefile' exists; overwrite? (y/n) y
(in helper) generating makefile for pkg "helper"
'Makefile' exists; overwrite? (y/n) y
(in .) generating makefile for cmd "lime-riki"
'view/Makefile' exists; overwrite? (y/n) y
(in view) generating makefile for pkg "view"
Makefile:41: *** missing separator.  Stop.
$ which gb | xargs ls -l
-rwxr-xr-x 1 bryan bryan 2303887 2011-12-08 08:12 /home/bryan/local/bin/gb
$
```

The timestamp on the executable agrees that it has been just been installed (as it is _now_ 2011-12-08 8:16).

I should have mentioned first that I install go-gb from googlecode because I was under the impression it was preferred.

**Comment by skelterjohn** [comment]
the git and googlecode versions are synchronized (albeit in an ad-hoc kind
of way).

And I checked, the "release" release (I am on weekly) of gb has that bug,
sorry! I'll fix it.

On Thu, Dec 8, 2011 at 11:17 AM, Bryan Matsuo <
reply@reply.github.com

**Comment by bmatsuo** [comment]
Cool, thanks. =)

**Comment by skelterjohn** [comment]
fixed
