### ISSUE TITLE
Error return value is being clobbered in defer

### ISSUE THREAD

**Issue by jbussdieker** [skelterjohn/go-gb#31]
gvm (https://github.com/moovweb/gvm) installs gb using goinstall so I was hoping you could fix a minor issue in the go.r60.3 tag. It seems this line https://github.com/skelterjohn/go-gb/blob/go.r60.3/gb/pkg.go#L986 is masking valid errors that would otherwise be returned.
## Repro

go: release.r60.3
gb: go.r60.3
1. Make a test with invalid Go syntax such that it won't compile
2. gb -t
3. echo $?

The result is 0 so automation software thinks that tests that don't compile are successful :(
## How I fixed it:

Change:

```
err = os.RemoveAll(testdir)
```

To:

```
rm_err := os.RemoveAll(testdir)
if err == nil { err = rm_err }
```

**Comment by skelterjohn** [comment]
Thanks for the bug report.

This bug has been fixed in the latest version of gb for the weekly version
of go. I strongly recommend for you to move to weekly as well, as the
current weekly is RC1 for Go 1.
- John

On Sat, Mar 17, 2012 at 5:21 AM, jbussdieker <
reply@reply.github.com

**Comment by jbussdieker** [comment]
Unfortunately we use gb.cfg so updating to the latest will require a fairly large change. I did check the latest release branch and it is fixed there however support for gb.cfg appears to have been removed (Is there an ignore=true option elsewhere now?). I appreciate your prompt response but I'm hoping you'll reconsider the fix to the go.r60.3 tag.

Regards,

-Josh

**Comment by skelterjohn** [comment]
I never removed gb.cfg functionality.

Can you say a little more about the context, and perhaps copy me the
contents? Maybe there is a bug, or maybe just a misunderstanding.

On Sat, Mar 17, 2012 at 8:20 PM, jbussdieker <
reply@reply.github.com

**Comment by jbussdieker** [comment]
Perhaps so... I tried to look for where gb.cfg was implemented in the release branch but couldn't find it. We use the ignore=true feature to exclude examples folders and oddly named test folders from gb. This feature seems to work with the go.r60.3 tag but not with the release branch.
