### ISSUE TITLE
updates to Go's path.Walk

### ISSUE THREAD

**Issue by XULRunner42** [skelterjohn/go-gb#8]
There is something wrong since HG#7651 that breaks the go-gb build.

To reproduce: pull and update go source, build all.bash, and try to rebuild go-gb

Output of build:

6g -o _go_.6 build.go deps.go gb.go goinstall.go make.go pkg.go gofmt.go runext.go util.go files.go usage.go cgo.go query.go genmake.go 
pkg.go:154: undefined: path.Walk
make: **\* [_go_.6] Error 1

**Comment by skelterjohn** [comment]
Pull the latest version :) I fixed this not one hour ago.

**Comment by XULRunner42** [comment]
You are on top of things :) thanks!

**Comment by skelterjohn** [comment]
I certainly appreciate the report, though. It's nice to know someone is actually using this stuff!
